import Config from 'react-native-config';

export const ENVIRONMENT_VARIABLES = {
  OPEN_WEATHER_API_BASE_URL: Config.OPEN_WEATHER_API_BASE_URL,
  OPEN_WEATHER_API_ICON_URL: Config.OPEN_WEATHER_API_ICON_URL,
  OPEN_WEATHER_API_KEY: Config.OPEN_WEATHER_API_KEY,
};
